### ISSUE TITLE
Admin Interface: Todo

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Kuirl#7]
On project and user profile page:
- [x] update session information in local storage: add project's shortcode, where the user is admin
- [x] is logged-in user sysAdmin or projectAdmin? if false: don't load project members, groups and ontology editor
- [ ] ~~in case of project admin: he's not allowed to see all users and to add one of them to the project --> talk with Ivan~~  --> postponed
- [x] disable collaboration, groups and data model tab for "normal" project members
- [x] fix gravatar image size by adding s=256 to the url; this should be fixed in @knora/action module
- [x] add gravatar to the user menu
- [x] edit user profile in the sidebar or in dialog box and remove edit user form from account
- [x] edit user profile in dialog box; will be used in collaboration
- [x] edit user's password in dialog box; will be used in collaboration
- [x] fix password form: add hidden username and second dialog box for sys admin
- [ ] ~~project search field in list of projects~~ --> postponed
- [x] move all admin forms to the material dialog box

**Comment by kilchenmann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kuirl: admin interface](https://trello.com/c/zE2Ti9Lp/69-kuirl-admin-interface)

**Comment by kilchenmann** [comment]
Password form: Fix warning
[DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq)
